### ISSUE TITLE
Traceback (most recent call last):   File "\pdo_import.py", line 142, in execute     bm.faces.new(indicies) ValueError: faces.new(verts): face already exists  location: <unknown location>:-1

### ISSUE THREAD

**Issue by ningningazz** [Coreforge/blender-pdo-import#1]
Traceback (most recent call last):
  File "\pdo_import.py", line 142, in execute
    bm.faces.new(indicies)
ValueError: faces.new(verts): face already exists

location: <unknown location>:-1
<img width="678" alt="image" src="https://github.com/Coreforge/blender-pdo-import/assets/149087094/559a3bdc-418f-424c-a6c4-a1e1ea604f2d">

**Comment by Coreforge** [comment]
Which blender version were you using (and which pepakura version was the file saved with, if you know that)? 
I just quickly tried a test model exported with pep5 and it still worked, so I don't think pep5 has broken anything (too much) so far.

If it's a public file, would you be able to share it? Otherwise, I can just add a try-except block to keep the importer from crashing.
