### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nathanite241** [Coreforge/blender-pdo-import#2]
Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\addons\pdo_import.py", line 94, in execute
    string_1 = decode(encoding,f.read(text_length))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\addons\pdo_import.py", line 34, in decode
    return data.decode(encoding="utf-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 103: invalid start byte

**Comment by Coreforge** [comment]
Can you share the file you tried to import (if it's one you're allowed to share)? I can't really debug without a test file that causes the issue.
